---
title: "Untitled"
output: html_document
---

```{r libraries, warning=FALSE,message=FALSE}
library(tidyverse)
library(data.table)

```

```{r new_league_data, warning=FALSE,message=FALSE}
old_league_data <- engsoccerdata::england
new_league_data <- readRDS("../rob_data/new_league_data.rds") %>%
  rename(goaldif = goal_dig)


new_league_data <- new_league_data %>%
  mutate(home = gsub("Brighton and Hove", "Brighton & Hove", home),
         visitor = gsub("Brighton and Hove", "Brighton & Hove", visitor)) %>%
  mutate(home = gsub("Yeovil Town", "Yeovil", home),
         visitor = gsub("Yeovil Town", "Yeovil", visitor)) %>%
  mutate(home = gsub("Cheltenham Town", "Cheltenham", home),
         visitor = gsub("Cheltenham Town", "Cheltenham", visitor)) %>%
  mutate(home = gsub("Stevenage", "Stevenage Borough", home),
         visitor = gsub("Stevenage", "Stevenage Borough", visitor))

old_league_teams <- c(old_league_data$home, old_league_data$visitor) %>%
  unique()
new_league_teams <- c(as.character(new_league_data$home), as.character(new_league_data$visitor)) %>%
  unique()

new_league_teams[!new_league_teams %in% old_league_teams]


full_league_data <- rbind(old_data, new_data)
```

```{r new_fa_data, warning=FALSE,message=FALSE}
old_fa_data <- engsoccerdata::facup
new_fa_data <- readRDS("../rob_data/new_fa_cup_data.rds") %>%
  mutate(home = gsub("^ \\([0-9]\\)", "", home),
         visitor = gsub("^ \\([0-9]\\)", "", visitor)) %>%
  mutate(home = gsub("Brighton and Hove", "Brighton & Hove", home),
         visitor = gsub("Brighton and Hove", "Brighton & Hove", visitor)) %>%
  mutate(home = gsub("Yeovil Town", "Yeovil", home),
         visitor = gsub("Yeovil Town", "Yeovil", visitor)) %>%
  mutate(home = gsub("Cheltenham Town", "Cheltenham", home),
         visitor = gsub("Cheltenham Town", "Cheltenham", visitor)) %>%
  mutate(home = gsub("Stevenage", "Stevenage Borough", home),
         visitor = gsub("Stevenage", "Stevenage Borough", visitor)) %>%
   mutate(home = gsub("Solihull Moors", "Solihull Borough", home),
         visitor = gsub("Solihull Moors", "Solihull Borough", visitor)) %>%
   mutate(home = gsub("Guiseley", "Guiseley AFC", home),
         visitor = gsub("Guiseley", "Guiseley AFC", visitor)) %>%
   mutate(home = gsub("Billericay Town", "Billericay", home),
         visitor = gsub("Billericay Town", "Billericay", visitor))
 

old_fa_teams <- c(old_fa_data$home, old_fa_data$visitor) %>%
  unique()
new_fa_teams <- c(as.character(new_fa_data$home), as.character(new_fa_data$visitor)) %>%
  unique()

new_fa_teams[!new_fa_teams %in% old_fa_teams]

full_fa_data <- rbind(old_fa_data, new_fa_data)

```

```{r new_lc_data, warning=FALSE,message=FALSE}
old_lc_data <- read.csv("../data-raw/leagucuptest.csv",
                        stringsAsFactors = FALSE) %>%
  mutate(Date = ifelse(Season == 1967 & grepl("1997", Date), gsub("1997", "1967", Date), Date)) %>%
  mutate(Date = as.Date(Date, "%d/%m/%Y")) %>%
  select(Date, Season, home, visitor, FT, hgoal, vgoal, round, tie, leg, aet, pens, Venue, attendance, northsouth) %>%
  mutate(home = gsub("Sunderland AFC", "Sunderland", home),
         visitor = gsub("Sunderland AFC", "Sunderland", visitor)) %>%
  mutate(home = gsub("Dagenham & Redbridge", "Dagenham and Redbridge", home),
         visitor = gsub("Dagenham & Redbridge", "Dagenham and Redbridge", visitor))
  
new_lc_data <- readRDS("../rob_data/league_cup_new_data.rds") %>%
  select(Date, Season, home, visitor, FT, hgoal, vgoal, round, tie, leg, aet, pens, Venue, attendance, northsouth) %>%
  mutate(home = gsub("Stevenage", "Stevenage Borough", home),
       visitor = gsub("Stevenage", "Stevenage Borough", visitor)) %>%
  mutate(home = gsub("Chester City", "Chester", home),
         visitor = gsub("Chester City", "Chester", visitor))


old_lc_teams <- c(old_lc_data$home, old_lc_data$visitor) %>%
  unique()
new_lc_teams <- c(as.character(new_lc_data$home), as.character(new_lc_data$visitor)) %>%
  unique()

new_lc_teams[!new_lc_teams %in% old_lc_teams]

full_lc_data <- rbind(old_lc_data, new_lc_data)

```
