---
title: "Untitled"
output: html_document
---

```{r libraries, warning=FALSE,message=FALSE}
library(tidyverse)
library(data.table)
library(rvest)

get_match_data <- function(link, cup_year) {
  check <<- link
  read <- read_html(link)
  
  date <- read %>% 
    html_nodes("h1") %>%
    html_text() %>%
    gsub(".*, ", "", .) %>%
    as.Date(., "%d %B %Y")
  
  season <- cup_year
  
  home <- read %>%
    html_nodes(".home .teamname a") %>%
    html_text()
  visitor <- read %>%
    html_nodes(".away .teamname a") %>%
    html_text()
  
  hgoal <- read %>%
    html_nodes(".home .score") %>%
    html_text() %>%
    gsub(" \\(.*", "", .) %>%
    as.numeric()
  vgoal <- read %>%
    html_nodes(".away .score") %>%
    html_text() %>%
    gsub(" \\(.*", "", .) %>%
    as.numeric()
  
  FT <- paste0(hgoal, "-", vgoal)
  
  round_info <- read %>%
    html_nodes(".basicData tr:nth-child(3) td+ td") %>%
    html_text() %>%
    gsub("League Cup ", "", .)
  
  if(grepl("[0-9].. round", round_info)) {
    round <- as.numeric(substr(round_info, 1, 1))
  } else {
    round <- gsub(" .*", "", round_info)
  }
  
  if(grepl("leg", round_info)) {
    leg <- gsub("(.*)([0-9].. leg)", "\\2", round_info) %>%
      gsub("[A-Za-z]", "", .) %>%
      as.numeric()
  } else {
    leg <- 1
  }
  
  #not always but 11v11 doesn't seem to list 1st replays
  #for league cup post 2000 doesn't seem to matter
  tie <- "initial"
  
  pens <- read %>%
    html_nodes(".score") %>%
    html_text()
  
  if(all(grepl("\\(", pens))) {
    pen_score <- gsub(".*\\(", "", gsub("\\)$", "", pens)) %>%
      paste(., collapse = "-")
  } else {
    pen_score <- NA
  }
  
  extra_time <- read %>% 
    html_nodes("#pageContent > div.match-report > div.match > div > div.comments.match") %>%
    html_text()
  
  if(length(extra_time) > 0) {
     if(grepl("extra time", extra_time)) {
       aet <- "yes"
     } else {
       aet <- NA
     }
  } else {
    aet <- NA
  }

  Venue <- read %>%
    html_nodes(".basicData tr:nth-child(4) td+ td") %>%
    html_text()
  
  attendance <- read %>%
    html_nodes(".basicData tr:nth-child(5) td+ td") %>%
    html_text()
  
  northsouth <- NA
  
  data <- data.frame(Date = date, Season = season,
                     home = home, visitor = visitor,
                     FT = FT,
                     round = round, tie = tie, leg = leg,
                     aet = aet, pens = pen_score,
                     Venue = Venue, attendance = attendance,
                     northsouth = northsouth,
                     hgoal = hgoal, vgoal = vgoal
                     )
}

```

```{r scrape_league_cup, warning=FALSE,message=FALSE}
year_links <- c("https://www.11v11.com/competitions/league-cup/2007/", 
                "https://www.11v11.com/competitions/league-cup/2015/",
                "https://www.11v11.com/competitions/league-cup/2016/",
                "https://www.11v11.com/competitions/league-cup/2017/",
                "https://www.11v11.com/competitions/league-cup/2018/")

league_cup_data <- lapply(year_links, function(link) {
  cup_year <- as.numeric(gsub(".*league-cup\\/", "", gsub("\\/$", "", link))) - 1
  match_links <- read_html(paste0(link, "matches/")) %>%
    html_nodes(".score a") %>%
    html_attr("href") %>%
    paste0("https://www.11v11.com", .) %>%
    unlist() %>%
    unique()
  
  data <- lapply(match_links, get_match_data, cup_year = cup_year) %>%
    do.call(rbind, .)
}) %>%
  do.call(rbind, .)

```


