---
title: "Untitled"
output: html_document
---

```{r libraries, warning=FALSE,message=FALSE}
library(engsoccerdata)
library(data.table)
library(tidyverse)
```

```{r load_data, warning=FALSE,message=FALSE}
league_cup <- read.csv("./data-raw/leaguecup.csv")

facup <- engsoccerdata::facup
```

```{r league_cup, warning=FALSE,message=FALSE}
lc_test <- league_cup %>%
  mutate(tie = case_when(
    replay == 0 ~ "initial",
    replay == 1 ~ "replay1",
    replay == 2 ~ "replay2",
    replay == 3 ~ "replay3",
    replay == "check" ~ "check_replay_data"
  )) %>%
  mutate(aet = gsub("Y", "yes", aet)) %>%
  select(Date = Date1, Season, home = home1, visitor = away1, FT = FT2, round = round1, tie, leg, aet, pens = pens, Venue = venue, attendance = Attendance, northsouth) %>%
  mutate(hgoal = as.numeric(gsub("-.*", "", FT))) %>%
  mutate(vgoal = as.numeric(gsub("[0-9]*-", "", FT))) %>%
  mutate(match_id = 1:nrow(.))

write.csv(lc_test, "leagucuptest.csv")
```

```{r}
which(!grepl("[0-9]*-[0-9]*", lc_test$FT))


```
```{r add_lc_dates}
#lc_test$Date <- as.Date(lc_test$Date)

#lc_test$Date[329] <- "1985-03-24"
#lc_test$Date[330] <- "1985-04-20"


table(lc_test$Season[which(is.na(lc_test$Date))])

```

