---
title: "Untitled"
output: html_document
---

```{r libraries, warning=FALSE,message=FALSE}
library(tidyverse)
library(data.table)
library(rvest)
library(stringr)

```

```{r lc_scrape_func, warning=FALSE,message=FALSE}
get_lc_match_data <- function(link, cup_year) {
  check <<- link
  read <- read_html(link)
  
  date <- read %>% 
    html_nodes("h1") %>%
    html_text() %>%
    gsub(".*, ", "", .) %>%
    as.Date(., "%d %B %Y")
  
  season <- cup_year
  
  home <- read %>%
    html_nodes(".home .teamname a") %>%
    html_text()
  visitor <- read %>%
    html_nodes(".away .teamname a") %>%
    html_text()
  
  hgoal <- read %>%
    html_nodes(".home .score") %>%
    html_text() %>%
    gsub(" \\(.*", "", .) %>%
    as.numeric()
  vgoal <- read %>%
    html_nodes(".away .score") %>%
    html_text() %>%
    gsub(" \\(.*", "", .) %>%
    as.numeric()
  
  FT <- paste0(hgoal, "-", vgoal)
  
  round_info <- read %>%
    html_nodes(".basicData tr:nth-child(3) td+ td") %>%
    html_text() %>%
    gsub("League Cup ", "", .)
  
  if(grepl("[0-9].. round", round_info)) {
    round <- as.numeric(substr(round_info, 1, 1))
  } else {
    round <- gsub(" .*", "", round_info)
  }
  
  if(grepl("leg", round_info)) {
    leg <- gsub("(.*)([0-9].. leg)", "\\2", round_info) %>%
      gsub("[A-Za-z]", "", .) %>%
      as.numeric()
  } else {
    leg <- 1
  }
  
  #not always but 11v11 doesn't seem to list 1st replays
  #for league cup post 2000 doesn't seem to matter
  tie <- "initial"
  
  pens <- read %>%
    html_nodes(".score") %>%
    html_text()
  
  if(all(grepl("\\(", pens))) {
    pen_score <- gsub(".*\\(", "", gsub("\\)$", "", pens)) %>%
      paste(., collapse = "-")
  } else {
    pen_score <- NA
  }
  
  extra_time <- read %>% 
    html_nodes("#pageContent > div.match-report > div.match > div > div.comments.match") %>%
    html_text()
  
  if(length(extra_time) > 0) {
     if(grepl("extra time", extra_time)) {
       aet <- "yes"
     } else {
       aet <- NA
     }
  } else {
    aet <- NA
  }

  Venue <- read %>%
    html_nodes(".basicData tr:nth-child(4) td+ td") %>%
    html_text()
  
  attendance <- read %>%
    html_nodes(".basicData tr:nth-child(5) td+ td") %>%
    html_text()
  
  northsouth <- NA
  
  data <- data.frame(Date = date, Season = season,
                     home = home, visitor = visitor,
                     FT = FT,
                     round = round, tie = tie, leg = leg,
                     aet = aet, pens = pen_score,
                     Venue = Venue, attendance = attendance,
                     northsouth = northsouth,
                     hgoal = hgoal, vgoal = vgoal
                     )
}

```

```{r league_scrape_func, warning=FALSE,message=FALSE}
get_league_match_data <- function(link, league_season, division) {
  check <<- link
  read <- read_html(link)
  
  date <- read %>% 
    html_nodes("h1") %>%
    html_text() %>%
    gsub(".*, ", "", .) %>%
    as.Date(., "%d %B %Y")
  
  season <- league_season
  division <- division
  tier <- division
  
  home <- read %>%
    html_nodes(".home .teamname a") %>%
    html_text()
  visitor <- read %>%
    html_nodes(".away .teamname a") %>%
    html_text()
  
  hgoal <- read %>%
    html_nodes(".home .score") %>%
    html_text() %>%
    gsub(" \\(.*", "", .) %>%
    as.numeric()
  vgoal <- read %>%
    html_nodes(".away .score") %>%
    html_text() %>%
    gsub(" \\(.*", "", .) %>%
    as.numeric()
  
  FT <- paste0(hgoal, "-", vgoal)
  
  if(hgoal == vgoal) {
    result = "D"
  } else {
    if(hgoal > vgoal) {
      result = "H"
    } else {
      result = "A"
    }
  }
  
  data <- data.frame(Date = date, Season = season,
                     home = home, visitor = visitor,
                     FT = FT,
                     hgoal = hgoal, vgoal = vgoal,
                     division = division, tier = tier,
                     totgoal = hgoal+vgoal,
                     goal_dig = hgoal - vgoal,
                     result = result
                     )
}

```

```{r fa_scrape_func, warning=FALSE,message=FALSE}
get_fa_match_data <- function(link, cup_year) {
  check <<- link
  read <- read_html(link)
  
  date <- read %>% 
    html_nodes("h1") %>%
    html_text() %>%
    gsub(".*, ", "", .) %>%
    as.Date(., "%d %B %Y")
  
  season <- cup_year
  
  home <- read %>%
    html_nodes(".home .teamname") %>%
    html_text() %>%
    str_replace_all(., "[\t\n\t0]" , "") %>%
    gsub("^[0-9]", "", .)
  visitor <- read %>%
    html_nodes(".away .teamname") %>%
    html_text() %>%
    str_replace_all(., "[\t\n\t0]" , "")%>%
    gsub("^[0-9]", "", .)

  hgoal <- read %>%
    html_nodes(".home .score") %>%
    html_text() %>%
    gsub(" \\(.*", "", .) %>%
    as.numeric()
  vgoal <- read %>%
    html_nodes(".away .score") %>%
    html_text() %>%
    gsub(" \\(.*", "", .) %>%
    as.numeric()
  
  FT <- paste0(hgoal, "-", vgoal)
  
  round_info <- read %>%
    html_nodes(".basicData tr:nth-child(3) td+ td") %>%
    html_text() %>%
    gsub("FA Cup ", "", .)
  
  if(grepl("[0-9].. round", round_info)) {
    round <- as.numeric(substr(round_info, 1, 1))
  } else {
    round <- gsub(" .*", "", round_info)
  }
  
  if(grepl("replay", round_info)) {
    tie <- "replay"
  } else {
    tie <- "initial"
  }

  pens <- read %>%
    html_nodes(".score") %>%
    html_text()
  
  if(all(grepl("\\(", pens))) {
    pen_score <- gsub(".*\\(", "", gsub("\\)$", "", pens)) 
    hp <- pen_score[1]
    vp <- pen_score[2]
    pen_score <- paste(pen_score, collapse = "-")
  } else {
    pen_score <- NA
    hp <- NA
    vp <- NA
  }
  
  if(!is.na(pen_score)) {
    pen <- "yes"
  } else {
    pen <- NA
  }
  
  extra_time <- read %>% 
    html_nodes("#pageContent > div.match-report > div.match > div > div.comments.match") %>%
    html_text()
  
  if(length(extra_time) > 0) {
     if(grepl("extra time", extra_time)) {
       aet <- "yes"
     } else {
       aet <- NA
     }
  } else {
    aet <- NA
  }

  Venue <- read %>%
    html_nodes(".basicData tr:nth-child(4) td+ td") %>%
    html_text()
  
  attendance <- read %>%
    html_nodes(".basicData tr:nth-child(5) td+ td") %>%
    html_text()
  
  if(round == "Semi-final" | round == "Final") {
    neutral <- "yes"
  } else {
    neutral <- NA
  }
  
  nonmatch <- NA
  notes <- NA

  data <- data.frame(Date = date, Season = season,
                     home = home, visitor = visitor,
                     FT = FT,
                     hgoal = hgoal, vgoal = vgoal,
                     round = round, tie = tie,
                     aet = aet, pen, pens = pen_score,
                     hp = hp, vp = vp,
                     Venue = Venue, attendance = attendance,
                     nonmatch = nonmatch, notes = notes, neutral = neutral
                     )
}

```

```{r scrape_league_cup, warning=FALSE,message=FALSE}
year_links <- c("https://www.11v11.com/competitions/league-cup/2007/", 
                "https://www.11v11.com/competitions/league-cup/2015/",
                "https://www.11v11.com/competitions/league-cup/2016/",
                "https://www.11v11.com/competitions/league-cup/2017/",
                "https://www.11v11.com/competitions/league-cup/2018/")

league_cup_data <- lapply(year_links, function(link) {
  cup_year <- as.numeric(gsub(".*league-cup\\/", "", gsub("\\/$", "", link))) - 1
  match_links <- read_html(paste0(link, "matches/")) %>%
    html_nodes(".score a") %>%
    html_attr("href") %>%
    paste0("https://www.11v11.com", .) %>%
    unlist() %>%
    unique()
  
  data <- lapply(match_links, get_lc_match_data, cup_year = cup_year) %>%
    do.call(rbind, .)
}) %>%
  do.call(rbind, .)

```

```{r scrape_league, warning=FALSE,message=FALSE}
old_data <- engsoccerdata::england %>%
  filter(Season > 2014)

year_links <- c("https://www.11v11.com/competitions/premier-league/2019/",
                "https://www.11v11.com/competitions/league-championship/2019/",
                "https://www.11v11.com/competitions/league-one/2019/",
                "https://www.11v11.com/competitions/league-two/2019/")

league_data <- lapply(year_links[4], function(link) {
  league_season <- as.numeric(gsub(".*\\/", "", gsub("\\/$", "", link))) - 1
  if(grepl("premier-league", link)) {
    division <- 1
  }
  if(grepl("championship", link)) {
    division <- 2
  }
  if(grepl("league-one", link)) {
    division <- 3
  }
  if(grepl("league-two", link)) {
    division <- 4
  }
  
  match_links <- read_html(paste0(link, "matches/")) %>%
    html_nodes(".score a") %>%
    html_attr("href") %>%
    paste0("https://www.11v11.com", .) %>%
    unlist() %>%
    unique()
  
  data <- lapply(match_links, get_league_match_data, league_season = league_season, division = division) %>%
    do.call(rbind, .)
}) %>%
  do.call(rbind, .)


new_data %>%
    mutate(home = case_when(
        grepl("Brighton and Hove", home) ~ "Brighton & Hove Albion",
        grepl("Cheltenham Town", home) ~ "Cheltenham",
        grepl("Stevenage", home) ~ "Stevenage Borough",
        grepl("Macclesfield Town", home) ~ "Macclesfield",
        grepl("Yeovil", home) ~ "Yeovil",
        TRUE ~ home
    )) %>%
      mutate(visitor = case_when(
        grepl("Brighton and Hove", visitor) ~ "Brighton & Hove Albion",
        grepl("Cheltenham Town", visitor) ~ "Cheltenham",
        grepl("Stevenage", visitor) ~ "Stevenage Borough",
        grepl("Macclesfield Town", visitor) ~ "Macclesfield",
        grepl("Yeovil", visitor) ~ "Yeovil",
        TRUE ~ visitor
    ))

```

```{r scrape_fac_cup, warning=FALSE,message=FALSE}
old_data <- engsoccerdata::facup %>% filter(Season > 2014)

fa_cup_data <- "https://www.11v11.com/competitions/fa-cup/2018/matches/" %>%
  read_html() %>%
  html_nodes(".score a") %>%
  html_attr("href") %>%
  unlist() %>%
  unique() %>%
  paste0("https://www.11v11.com", .) %>%
  lapply(., get_fa_match_data, cup_year = 2017) %>%
  do.call(rbind, .)
```
